
apiVersion: v1
kind: Service
metadata:
  name: photostudio-backend-service
  namespace: photostudio
spec:
  selector:
    app: photostudio-backend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
