
apiVersion: v1
kind: Service
metadata:
  name: photostudio-frontend-service
  namespace: photostudio
spec:
  selector:
    app: photostudio-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32080
