
apiVersion: v1
kind: Service
metadata:
  name: photostudio-service
  namespace: photostudio
spec:
  selector:
    app: photostudio-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000         
      targetPort: 3000    
      nodePort: 32000     
